name: priority_scheduling
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0-0.0.dev <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
dev_dependencies:
flutter:
  uses-material-design: true
